- name: Setup gpg key
  apt_key:
    url: https://downloads.cryft.network/cryftgo.gpg.key
    state: present

- name: Setup cryftgo repo
  apt_repository:
    repo: deb https://downloads.cryft.network/apt jammy main
    state: present

- name: Setup golang repo
  apt_repository:
    repo: ppa:longsleep/golang-backports 
    state: present

- name: Install go
  apt:
    name: golang
    state: latest

- name: Update git clone
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_folder }}"
    version: "{{ tag }}"
    update: yes
    force: yes

- name: Setup systemd
  template:
    src: templates/cryftgo.service.j2
    dest: /etc/systemd/system/cryftgo.service
    mode: 0755

- name: Create avalanche user
  user:
    name: "{{ ava_user }}"
    shell: /bin/bash
    uid: "{{ ava_uid }}"
    group: "{{ ava_group }}"

- name: Create avalanche config dir
  file:
    path: /etc/cryftgo
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory

- name: Create avalanche log dir
  file:
    path: "{{ log_dir }}"
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory

- name: Create avalanche database dir
  file:
    path: "{{ db_dir }}"
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory

- name: Build cryftgo
  command: ./scripts/build.sh
  args:
    chdir: "{{ repo_folder }}"

- name: Copy cryftgo binaries to the correct location
  command: cp build/cryftgo /usr/local/bin/cryftgo
  args:
    chdir: "{{ repo_folder }}"

- name: Configure avalanche 
  template:
    src: templates/conf.json.j2
    dest: /etc/cryftgo/conf.json
    mode: 0644

- name: Enable Avalanche
  systemd:
    name: cryftgo
    enabled: yes
